### ISSUE TITLE
Can't build it

### ISSUE THREAD

**Issue by bnjbvr** [denismerigoux/wasm2cretonne#1]
Bonjour,

It appears I can't build this with `cargo build`, because the `frontend` branch on your `cretonne` fork is actually missing. Any chance you could push it?

Also, is that correct that the binary utility in `src` displays the wast and CIL? Is there a way to enable only displaying the CIL?

(disclaimer, I'm looking into feeding valid random wasm binaries to wasm2cretonne and then pass the CIL files to Cretonne)

**Comment by denismerigoux** [comment]
Hi Ben,

Indeed I forgot to update my dependencies after my frontend pull request had been merged on Cretonne. It should work now. 

The binary utility indeed displays wast and CIL in the "interactive" mode but this binary is just here for testing purposes, the actual useful crate is in `lib/wasm2cretonne` and has the `translate_module` function which converts a valid wasm binary (`Vec<u8>`) into a list of CIL functions.

**Comment by denismerigoux** [comment]
I tested in on a couple big wasm modules (5~10 MB) and got no translation errors, tell me if you get one.

**Comment by bnjbvr** [comment]
Thanks, it works now!
